In [1]:
import logging
import glob
from pathlib import Path
import scipy.io.wavfile as wav
import numpy as np
import matplotlib.pyplot as plt

from scipy import signal
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

print(__doc__)

# Display progress logs on stdout
logging.basicConfig(level=logging.INFO, format='%(asctime)s %(message)s')

Automatically created module for IPython interactive environment


In [82]:
def load_raw_data(audio_path):
    samples_data = []
    sample_data_rates = []
    file_names = []
    label_encoder = preprocessing.LabelEncoder()

    for file in Path(audio_path).glob("**/*.wav"):
        if not file.is_file():  # Skip directories
            continue

        sample_rate, samples = wav.read(file)
        samples_data.append(samples)
        sample_data_rates.append(sample_rate)
        
        file_names.append(file.name)

    return samples_data, sample_data_rates, file_names

def get_wav_spectrogram(data, rate, file_name):
    print('Processing file: %s' %file_name)
    fig, ax = plt.subplots(1)
    fig.subplots_adjust(left = 0, right = 1, bottom = 0, top = 1)
    ax.axis('off')

    pxx, freqs, bins, im = ax.specgram(x = data, Fs = rate, noverlap = 384, NFFT = 512)
    ax.axis('off')

    DPI = fig.get_dpi()
    fig.set_size_inches(64.0/float(DPI), 64.0/float(DPI))
    
    fig.savefig(file_name, frameon = 'false')

def save_wav_spectogram_to_image(samples, sample_rates, file_names):
    img_dir = './images/'
    for index, sample in enumerate(samples):
        file_name = img_dir + (file_names[index].rsplit('.', 1)[0]) + '.png' # remove .wav
        get_wav_spectrogram(sample, sample_rates[index], file_name)


In [84]:
# Generate images.
#wav_data, sample_rates, file_names = load_raw_data('./recordings')
#spectogram_to_image(wav_data, sample_rates, file_names)

In [7]:
def get_data_from_spectogram_images(images_path):
    labels = []
    for file in Path(images_path).glob("**/*.png"):
        label = file.name.split('_')[0]
        labels.append(label)
    

array([array([ -6, -16, -10, ...,  12,  14,  17], dtype=int16),
       array([-7,  5,  1, ...,  5, -1, 16], dtype=int16),
       array([ 0, -2,  1, ...,  1,  1,  3], dtype=int16), ...,
       array([ 1,  8,  1, ..., -8,  1,  4], dtype=int16),
       array([ 1, 11, -6, ..., 10,  2,  2], dtype=int16),
       array([-374, -473, -560, ..., -302, -279, -329], dtype=int16)],
      dtype=object)